Disable mime in setup
portagenetwork/roadmap pull request #120
Opened 2022-01-18 22:35 UTC by pengyin-shan

Changes proposed in this PR:
- A update of README.md and CONTRIBUTION.md for 3.0 release
- Comment out the `rails mime_types:load` in `bin/setup` because it won't be part of 3.0 release

@lagoan the wiki belongs to its own repository so this PR doesn't include it (I will continue to work on wiki and update under #issue109). This PR contains the README update, Contribution guide update and `setup` file update.

2022-01-20 18:47 UTC, lagoan commented on .github/CONTRIBUTING.md
> +Once your code has been approved a member of the core development team will merge it into the development branch and nd include it in an upcoming release.
Just a small typo here, the sentence has an extra `nd`

2022-01-20 18:49 UTC, lagoan commented on README.md
> +<h1>DMP Assistant</h1>
I think we should keep the `##` way of defining headers in markdown

2022-01-20 18:51 UTC, lagoan commented on README.md
> +- [Latest Update](#overview)
I think this should be 

```
[Latest Update](#latest-update)
```

2022-01-20 18:52 UTC, lagoan requested changes
All looks good! 

I just noted some minor suggestions.

2022-01-20 20:25 UTC, pengyin-shan commented
> All looks good!
> 
> I just noted some minor suggestions.

Thank you! I made changes based on your view

2022-01-24 19:33 UTC, lagoan approved these changes
![LGTM!](https://media.giphy.com/media/2lQCBjuFMLCOvXno4l/giphy.gif)

2022-02-03 17:45 UTC, closed without merging