Remove broken links to Portage Network pages #339
portagenetwork/roadmap pull request #368
Opened 2023-07-13 21:07 UTC by 200455939-yashu

Fixes # .

Issues with the Links resolved

Changes proposed in this PR: [339](https://github.com/portagenetwork/roadmap/issues/339)
-

2023-07-14 17:26 UTC, lagoan requested changes
This is good work. We just need to remove those old links since we don't want old code to stay for long. If we are not using it we should remove it.

With any changes to text, we need to run the translation worflow. We will talk about that in a bit.

2023-07-14 17:26 UTC, lagoan commented on app/helpers/application_helper.rb
> +      'https://alliancecan.ca/en/services/research-data-management/learning-and-training/institutional-contacts'
We don't need to keep the old URLs now so we can remove these commented out code.

2023-07-17 19:19 UTC, lagoan requested changes
We just need an entry on the CHANGELOG file and we will be done with this PR! 😄

2023-07-17 19:19 UTC, lagoan commented on CHANGELOG.md
All looks good! Just make sure to add an entry to CHANGELOG. This is a minor change and we need to keep a track of our changes.

2023-07-17 19:25 UTC, 200455939-yashu commented on app/helpers/application_helper.rb
> +      'https://alliancecan.ca/en/services/research-data-management/learning-and-training/institutional-contacts'
Updated this

2023-07-18 20:49 UTC, lagoan approved these changes
![GW!](https://media.giphy.com/media/T9SzftdKiHZTzmfluU/giphy.gif)

2023-07-18 20:51 UTC, merged