Merge upstream releases v4.0.0, v4.0.1, and v4.0.2
portagenetwork/roadmap pull request #474
Opened 2023-10-06 22:17 UTC by aaronskiba

2023-10-30 15:17 UTC, 200455939-yashu commented on app/models/concerns/exportable_plan.rb
> +      csv << []
Lines 54 and 55 are the same!

2023-10-30 15:24 UTC, 200455939-yashu commented on app/models/concerns/exportable_plan.rb
> +    return false unless hash[:research_outputs].present? && hash[:research_outputs].any?
can we directly call `retrun unless` instead of `return false unless` ?

2023-10-30 15:25 UTC, 200455939-yashu commented on app/models/concerns/exportable_plan.rb
> +    csv << []
Do we need lines 227 and 228?

2023-11-03 21:02 UTC, 200455939-yashu approved these changes, later dismissed
Awesome Work 😇👏

2023-11-15 21:34 UTC, lagoan requested changes
Looks like good work! We should find time to go through the change together.

2023-11-15 21:34 UTC, lagoan commented on Gemfile
> +  gem 'rubocop', '~> 1.44.1' # Pinned to align with upstream v4.0.2
We should add another comment on the line above pinning the gem specifying it is for dmp assistant

2023-11-15 21:34 UTC, lagoan commented on Gemfile
> +  # gem 'rubocop-thread_safety'
@aaronskiba do we know why these rubocop gems were commented out?

2023-11-15 21:34 UTC, lagoan commented on app/models/concerns/exportable_plan.rb
> +    return false unless hash[:research_outputs].present? && hash[:research_outputs].any?
I think here we want the false value explicitly instead of nil with just the return statement. This logic could be simplified though, we will be able to help more with this once we are more involved with core development.

2023-11-15 21:34 UTC, lagoan commented on config/environments/development.rb
> +Rails.application.routes.default_url_options[:host] = Rails.application.secrets.dmproadmap_host
We had a conversation before about the use of ENV variables. In this case, we could continue to use it since it is for the development environment, we use a lot of these variables at the moment. The production environment is where we handle it differently at this time.

2023-11-15 21:34 UTC, lagoan commented on config/environments/production.rb
> +require 'active_support/core_ext/integer/time'
We've commented out the code where this is used so we can ignore this as well.

```
# config.active_record.database_selector = { delay: 2.seconds }
```

2023-11-15 21:34 UTC, lagoan commented on config/environments/production.rb
> +  # config.active_record.database_resolver_context = ActiveRecord::Middleware::DatabaseSelector::Resolver::Session
Is upstream using this configuration ? If not we should remove it as it will only add noise to our config file and at this time I dont see a use case for us for multiple databases.

2023-11-20 18:10 UTC, lagoan commented on config/environments/development.rb
> +Rails.application.routes.default_url_options[:host] = Rails.application.secrets.dmproadmap_host
@aaronskiba Will add ENV variable backl

2023-12-19 17:13 UTC, lagoan requested changes
Great progress @aaronskiba , this is a huge PR so there are only a few things to look at.

2023-12-19 17:13 UTC, lagoan commented on CHANGELOG.md
> +
For merging this file we can add the changes on the same indentation level as they are changes that come into that release. Nice idea of keeping the merged versions, we should keep that.

2023-12-19 17:13 UTC, lagoan commented on app/views/orgs/_profile_form.html.erb
>              <em class="sr-only"></em>
I think we were going to verify the tooltips were working. Did we verify this?

2023-12-20 16:52 UTC, lagoan approved these changes
![good job!](https://media.giphy.com/media/xjc9ZGqcMukD1EJo9r/giphy.gif)

2023-12-20 17:07 UTC, merged