Re-Implement Email Confirmation
portagenetwork/roadmap pull request #923
Opened 2024-10-07 19:16 UTC by aaronskiba

Fixes * 

Changes proposed in this PR:
- Re-implement email confirmation via Devise's `:confirmable` module
- Add rake task that after execution, all non-superadmins will have to confirm their email to use the app
- Customise UX flow for existing, unconfirmed users

2024-10-09 16:04 UTC, lagoan requested changes
Good work all around ! I added just some comments on minor changes.

2024-10-09 16:04 UTC, lagoan commented on app/models/user.rb
> +      confirmed_at: Time.now
We should follow devise behaviour and have the confirmed_at value set as  `confirmed_at: Time.now.to_utc`

https://github.com/heartcombo/devise/blob/72884642f5700439cc96ac560ee19a44af5a2d45/lib/devise/models/confirmable.rb#L87

2024-10-09 16:04 UTC, lagoan commented on config/locales/translation.en-CA.yml
> +        <a href="/users/confirmation/new" class="a-orange">(Click to request a new confirmation email)</a>
Right now we are sending the email verification message sent when the user tries to log in and is not verified. What do you think about letting the user know about this sent email in this message instead of asking the user to request the email confirmation again ?

2024-10-09 16:04 UTC, lagoan commented on config/locales/translation.en-CA.yml
> +        subject: Confirm your DMP Assistant account
Good catch for this change !

2024-10-09 16:04 UTC, lagoan commented on config/locales/translation.fr-CA.yml
> +        <a href="/users/confirmation/new" class="a-orange">(Cliquez pour demander un nouvel e-mail de confirmation)</a>
Same as above to let the user know about the email that was already sent.

2024-10-09 16:04 UTC, lagoan commented on spec/factories/users.rb
> +    confirmed_at { Time.now }
Same as above to use ``confirmed_at { Time.now.to_utc }``

2024-10-10 20:04 UTC, aaronskiba commented on config/locales/translation.en-CA.yml
> +        <a href="/users/confirmation/new" class="a-orange">(Click to request a new confirmation email)</a>
Good question. This flash message is actually only rendered when the user already has an outstanding confirmation. An additional confirmation email not be auto-sent in this case and they will have to manually request a new one.

If a user is unconfirmed and has no outstanding confirmation token, then a different message will render after they attempt to sign in (specifically, `devise.registrations.signed_up_but_unconfirmed`).

```
3.1.4 :001 > I18n.t('devise.registrations.signed_up_but_unconfirmed')
 => "A message with a confirmation link has been sent to your email address. Please open the link to activate your account. If you do not receive the confirmation email, please check your spam filter." 
```

```ruby
# app/models/user.rb
def confirmation_instructions_handled?
  confirmed? || confirmation_token.present?
end
```

```ruby
# app/controllers/sessions_controller.rb
unless existing_user.confirmation_instructions_handled?
  handle_confirmation_instructions(existing_user)
  return
end

def handle_confirmation_instructions(user)
  user.send_confirmation_instructions
  flash[:notice] = _('A confirmation email has been sent to you. Please check your inbox to confirm your account.')
  flash[:notice] = I18n.t('devise.registrations.signed_up_but_unconfirmed')
  redirect_to root_path
end
```

2024-10-10 20:33 UTC, aaronskiba commented on app/models/user.rb
> +      confirmed_at: Time.now
Cool, I was unsure about this one. I'm doing a little more testing, and we might be safe. Although the output of `Time.now` reflects my current timezone, Whether I try saving `Time.now` or `Time.now.utc`, it seems to always be saved to the DB in its UTC form:

```
3.1.4 :001 > user = User.last
  User Load (3.2ms)  SELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1  [["LIMIT", 1]]
 => #<User id: 26480, firstname: "test", surname: "test", email: "helloworld@abc.com", created_at: ...

3.1.4 :002 > user.updated_at
 => Thu, 10 Oct 2024 20:21:56.229255000 UTC +00:00

3.1.4 :003 > user.update(updated_at: Time.now)
  TRANSACTION (2.5ms)  BEGIN
  Language Load (2.2ms)  SELECT "languages".* FROM "languages" WHERE "languages"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]                                                                        
  Org Load (3.1ms)  SELECT "orgs".* FROM "orgs" WHERE "orgs"."id" = $1 LIMIT $2  [["id", 59], ["LIMIT", 1]]                                                                                           
  User Update (3.7ms)  UPDATE "users" SET "updated_at" = $1 WHERE "users"."id" = $2  [["updated_at", "2024-10-10 20:23:35.082699"], ["id", 26480]]                                                    
  TRANSACTION (13.9ms)  COMMIT                                                               
 => true

3.1.4 :004 > user.reload
  User Load (2.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 26480], ["LIMIT", 1]]                                                                                    
 => #<User id: 26480, firstname: "test", surname: "test", email: "helloworld@abc.com", created_at: "2024-10-10 18:02:13.546883000 +0000", updated_at: "2024-10-10 20:23:35.082699000 +0000", other_organisation: nil, dmponline3: nil, accept_terms: true, org_id: 59, api_token: nil, language_id: 1, recovery_email: nil, active: true, department_id: nil, last_api_access: nil, prefs: nil>

3.1.4 :005 > user.updated_at
 => Thu, 10 Oct 2024 20:23:35.082699000 UTC +00:00 
3.1.4 :006 > user.update(updated_at: Time.now.utc)
  TRANSACTION (2.9ms)  BEGIN
  Language Load (2.7ms)  SELECT "languages".* FROM "languages" WHERE "languages"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]                                                                                    
  Org Load (2.3ms)  SELECT "orgs".* FROM "orgs" WHERE "orgs"."id" = $1 LIMIT $2  [["id", 59], ["LIMIT", 1]]                                                                                                       
  User Update (2.6ms)  UPDATE "users" SET "updated_at" = $1 WHERE "users"."id" = $2  [["updated_at", "2024-10-10 20:24:34.814186"], ["id", 26480]]                                                                
  TRANSACTION (13.4ms)  COMMIT                                                                           
 => true
 
3.1.4 :007 > user.reload
  User Load (3.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 26480], ["LIMIT", 1]]                                                                                                
 => #<User id: 26480, firstname: "test", surname: "test", email: "helloworld@abc.com", created_at: "2024-10-10 18:02:13.546883000 +0000", updated_at: "2024-10-10 20:24:34.814186000 +0000", other_organisation: nil, dmponline3: nil, accept_terms: true, org_id: 59, api_token: nil, language_id: 1, recovery_email: nil, active: true, department_id: nil, last_api_access: nil, prefs: nil>
 
3.1.4 :008 > user.updated_at
 => Thu, 10 Oct 2024 20:24:34.814186000 UTC +00:00
```

2024-10-15 20:55 UTC, lagoan commented on app/models/user.rb
> +      confirmed_at: Time.now
I am glad you checked that. We should still follow the gem's behaviour so we can catch any changes regardless.

2024-10-22 20:18 UTC, lagoan requested changes
Awesome work. Just a minor comment on how we are setting the time.

2024-10-22 20:18 UTC, lagoan commented on app/models/user.rb
> +      confirmed_at: Time.now
We should follow the original gem and use utc time. ``confirmed_at: Time.now.to_utc``

2024-10-22 20:20 UTC, aaronskiba commented on app/models/user.rb
> +      confirmed_at: Time.now
Sounds good. Sorry, still need to make these changes soon here.

2024-11-06 18:44 UTC, lagoan approved these changes, later dismissed
![LGTM](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcjYzcm4wcnJoNnA0dmg5ZnNoNGZjMWdhempiNXJkbG9odzVsZm5oZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5USTijryafZEQ/giphy.gif)

2024-11-06 18:50 UTC, lagoan approved these changes
LGTM!

2024-11-06 18:54 UTC, merged